CREATE USER IF NOT EXISTS ledgerservice WITH PASSWORD '12345';
CREATE DATABASE ledger;
REVOKE ALL PRIVILEGES ON DATABASE ledger FROM PUBLIC;
GRANT ALL PRIVILEGES ON DATABASE ledger TO USER ledgerservice;
